name: Deploy existing ECR image to ECS

on:
  push:
    branches: ["master"]

env:
  AWS_REGION: eu-west-2
  DOCKER_IMAGE_URI: manojavr/bene-dashboard-ui-image:latest
  ECS_CLUSTER: bp-collect-service-test
  ECS_SERVICE: bp-service-test-service  
  ECS_TASK_DEF: bp-service-test

jobs:
  deploy-to-ecs:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIAYJZDHK4U7IJSBWNA
        aws-secret-access-key: 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
        aws-region: ap-south-1

    - name: Fetch current task definition
      run: |
        aws ecs describe-task-definition --task-definition $ECS_TASK_DEF > task-def.json
        cat task-def.json | jq '.taskDefinition' > task-def-body.json

    - name: Update task definition with Docker Hub image
      run: |
        NEW_DEF=$(cat task-def-body.json | jq --arg IMAGE "$DOCKER_IMAGE_URI" \
          '(.containerDefinitions[0].image) |= $IMAGE')
        echo "$NEW_DEF" > new-task-def.json
        TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json | jq -r '.taskDefinition.taskDefinitionArn')
        echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

    - name: Update ECS service to use new task definition
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --task-definition ${{ env.TASK_DEF_ARN }} \
          --force-new-deployment
